sudo: required

services:
  - docker
  

before_install:
  - docker build -t nguyentaithao/travis-ci -f Dockerfile.dev .

script:
  - docker run nguyentaithao/travis-ci npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-687900780546"
  bucket_path: "docker-react"
  on:
    branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
